### ISSUE TITLE
"mvn test" fails with JDK 11

### ISSUE THREAD

**Issue by skanga** [ljnelson/helidon-mp-jpa#1]
[INFO]
[INFO] --- eclipselink-maven-plugin:2.7.1.1:modelgen (modelgen) @ helidon-mp-jpa ---
[INFO] JPA modelgen: Found 4 source files for potential processing
[INFO] JPA modelgen: Output directory: c:\apmnext\helidon\helidon-mp-jpa\target\generated-sources\apt
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.730 s
[INFO] Finished at: 2021-02-14T17:49:44-08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.ethlo.persistence.tools:eclipselink-maven-plugin:2.7.1.1:modelgen (modelgen) on project helidon-mp-jpa: Execution modelgen of goal com.ethlo.persistence.tools:eclipselink-maven-plugin:2.7.1.1:modelgen failed: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException: javax.xml.bind.JAXBException -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by ljnelson** [comment]
Hi!  I'm not surprised you've found a bug.  This project is out of date.  You should check out the [Helidon MP JPA guide](https://helidon.io/docs/v2/#/mp/guides/09_jpa), which tells you how to do it for real and in a supported way.

**Comment by ljnelson** [comment]
(For posterity: the version of Helidon used for this project was a version for which Java 8 was the only supported JDK version.  Between JDK 11 and Java 8 support for JAXB was removed from the core JDK.)
